# Datos completos de razas por especie
RAZAS_POR_ESPECIE = {
    'Perro': [
        'Labrador Retriever',
        'Pastor Alemán',
        'Golden Retriever',
        'Bulldog Francés',
        'Bulldog Inglés',
        'Poodle',
        'Beagle',
        'Yorkshire Terrier',
        'Dachshund',
        'Chow Chow',
        'Pomerania',
        'Chihuahua',
        'Pug',
        'Cocker Spaniel',
        'Schnauzer Miniatura',
        'Shiba Inu',
        'Akita',
        'Boxer',
        'Doberman Pinscher',
        'Rottweiler',
        'Pastor Australiano',
        'Border Collie',
        'Husky Siberiano',
        'Sabueso',
        'Setter Irlandés',
        'Bretón',
        'Weimaraner',
        'Vizsla',
        'Pointer Inglés',
        'Spaniel Japonés',
        'Pekingés',
        'Cavalier King Charles Spaniel',
        'Boston Terrier',
        'Whippet',
        'Galgo Italiano',
        'Jack Russell Terrier',
        'Terrier Tibetano',
        'Lhasa Apso',
        'Shih Tzu',
        'Maltés',
        'Bichón Frisé',
        'Caniche Toy',
        'Fox Terrier',
        'Airedale Terrier',
        'Basset Hound',
        'Saint Bernard',
        'Gran Danés',
        'Mastín Inglés',
        'Terranova',
        'Collie',
        'Shar Pei',
        'Staffordshire Bull Terrier',
        'Pit Bull Terrier',
        'Cane Corso',
        'Dogo Argentino',
        'Mastín Español',
        'Otra Raza'
    ],
    'Gato': [
        'Persa',
        'Maine Coon',
        'Siamés',
        'Bengalí',
        'Rajah',
        'Manx',
        'Sphynx',
        'Scottish Fold',
        'Ragdoll',
        'Británico de Pelo Corto',
        'Ruso Azul',
        'Tonkinés',
        'Balinés',
        'Birmano',
        'Bombay',
        'Cornish Rex',
        'Devon Rex',
        'Gato de Pelo Largo',
        'Angora Turco',
        'Bosque de Noruega',
        'Kurilian Bobtail',
        'Munchkin',
        'Sokoke',
        'Turkish Van',
        'Selkirk Rex',
        'LaPerm',
        'California Spangled',
        'Ocicat',
        'Abisinio',
        'Ashera',
        'Serengeti',
        'Savannah',
        'Chausie',
        'Pixie Bob',
        'Gato Doméstico Común',
        'Otra Raza'
    ],
    'Conejo': [
        'Conejo de Angora',
        'Conejo Belier',
        'Conejo Neozelandés',
        'Conejo Californiano',
        'Conejo Chinchilla',
        'Conejo Gigante Flamenco',
        'Conejo Holandés',
        'Conejo Mini Lop',
        'Conejo Holandés Enano',
        'Conejo Satinado',
        'Conejo Lipizzano',
        'Conejo Himalayano',
        'Conejo Plata',
        'Conejo Tan',
        'Conejo Flamígero',
        'Conejo Mariposa Inglesa',
        'Conejo Palomino',
        'Conejo Arlequín',
        'Conejo de Pelo Corto Europeo',
        'Otra Raza'
    ],
    'Ave': [
        'Loro Verde',
        'Loro Gris Africano',
        'Guacamayo Azul y Amarillo',
        'Guacamayo Rojo',
        'Cacatúa Blanca',
        'Cacatúa de Cresta Amarilla',
        'Cacatúa Negra',
        'Pájaro Carpintero',
        'Canario',
        'Jilguero',
        'Diamante Mandarín',
        'Periquito Australiano',
        'Cotorra Argentina',
        'Loro Amazónico',
        'Loro Eclectus',
        'Loro Cabeza Roja',
        'Loro de Cabeza Negra',
        'Loro Vientre Rojo',
        'Faisán',
        'Gallina de Guinea',
        'Pava Real',
        'Otra Raza'
    ],
    'Roedor': [
        'Hámster Sirio',
        'Hámster Ruso',
        'Hámster Chino',
        'Hámster Enano',
        'Ratón Doméstico',
        'Rata Doméstica',
        'Conejillo de Indias',
        'Chinchilla',
        'Degú',
        'Ardilla Voladora',
        'Otra Raza'
    ],
    'Reptil': [
        'Serpiente Reina',
        'Serpiente de Maíz',
        'Boa Constrictor',
        'Iguana Verde',
        'Dragón Barbudo',
        'Camaleón Velado',
        'Tortuga Rusa',
        'Serpiente Real',
        'Gecko Leopardo',
        'Gecko Diurno',
        'Otra Raza'
    ],
    'Pez': [
        'Pez Dorado',
        'Carpa Koi',
        'Pez Beta',
        'Guppy',
        'Tetra Neón',
        'Pez Ángel',
        'Disco',
        'Pleco',
        'Bagre Rayado',
        'Rasbora',
        'Cabeza de Serpiente',
        'Cíclido Africano',
        'Pez Payaso',
        'Pez Cirujano',
        'Otra Raza'
    ]
}

ESPECIES = list(RAZAS_POR_ESPECIE.keys())
